<link rel="stylesheet" href="{{ URL::asset('assets/css/test.css') }}">
<div class="neon-card"><div class="neon-card-title"><div class="card-first-letter">H</div>ELLO</div><div class="neon-card-body-full">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, commodi. In impedit voluptas excepturi itaque nihil. Soluta, officia facere eligendi sed sint quis, voluptates cupiditate magni tempore facilis odio iure.
Voluptates nihil praesentium quasi voluptatem. Natus sed iusto, nisi dignissimos nobis aliquam sint reiciendis, aperiam ullam perferendis error ex reprehenderit quae labore eius unde placeat sapiente velit architecto! Consequuntur, fugiat.
Iure alias praesentium voluptatum, eveniet reiciendis odit! Eos dolore expedita, neque unde pariatur, laudantium iure, odit reprehenderit placeat ipsa ex aspernatur! Laudantium cum, optio numquam id beatae labore libero repellat.
Vel ratione rerum numquam similique, omnis, dolorum necessitatibus molestiae dicta qui eligendi eius quo. Odio, ratione incidunt molestias suscipit, quos voluptas reiciendis necessitatibus nostrum quo dolore nemo. Temporibus, eligendi velit!
Voluptatum dolor minus voluptatibus consequatur veniam quos dignissimos minima ipsam corporis, deserunt harum ratione expedita eius sit animi incidunt dolorum laboriosam reprehenderit pariatur itaque veritatis quaerat repellat! Nemo, fugit nulla!
Quas, possimus accusantium? Tempore, nemo? Recusandae doloremque, ad corporis harum, provident numquam nisi repellat aut autem voluptate cupiditate natus quae eos. Placeat suscipit ratione eius omnis distinctio debitis magni pariatur.
Deleniti, reiciendis. Et laboriosam aut sapiente deleniti alias cupiditate provident cum magnam perferendis quasi dolorem impedit amet veniam harum facere ducimus, repudiandae minus repellat hic doloremque, qui, iste neque molestiae.
Reprehenderit doloribus, facilis autem soluta velit ex vel recusandae, rem beatae saepe maxime laboriosam accusamus dolore qui quae, dolorum sapiente hic. Delectus, provident facere. Obcaecati, error. Rem dolorem maxime non!
Aspernatur provident similique possimus accusamus fugit ipsa, illum officiis saepe fugiat ut delectus ipsum iste, nulla, sit odio exercitationem sint. Odit magni sequi, voluptatibus et nesciunt excepturi explicabo inventore consectetur?
Cupiditate dolore inventore libero nesciunt voluptatibus autem quidem. Laboriosam commodi beatae sit et minus iste vero pariatur quo, voluptas obcaecati dolorem ex eveniet expedita, iure, unde distinctio in! Cupiditate, hic!
Quae aliquam placeat culpa! Iure distinctio adipisci est. Enim ipsa, voluptate expedita eaque culpa nam saepe quidem perferendis dolorem id maxime sint, deleniti neque odio illo officia optio omnis rerum.
Pariatur, error odio vitae nulla dolor animi repellendus quia, facere saepe eveniet porro deserunt nihil atque nostrum asperiores ratione reprehenderit voluptate quisquam, libero totam voluptatem natus. Dolores itaque modi placeat.
Laudantium autem dolorum reprehenderit magnam voluptatum quisquam harum, aliquid optio est sequi minus culpa blanditiis repudiandae architecto eius, aliquam quam. Totam, distinctio nobis! Esse quidem distinctio minima quia reprehenderit a.
Iure, corrupti libero ad, quidem labore atque dicta illo excepturi inventore, impedit nobis ratione corporis id beatae minus vero dignissimos unde nemo ea voluptates officia pariatur quo hic?
</div></div>
<br><br>
<div class="neon-card"><div class="neon-card-title"><div class="card-first-letter">H</div>ELLO</div><div class="neon-card-body-pic" style="background:blue;"></div><div class="neon-card-body">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, commodi. In impedit voluptas excepturi itaque nihil. Soluta, officia facere eligendi sed sint quis, voluptates cupiditate magni tempore facilis odio iure.
Voluptates nihil praesentium quasi voluptatem. Natus sed iusto, nisi dignissimos nobis aliquam sint reiciendis, aperiam ullam perferendis error ex reprehenderit quae labore eius unde placeat sapiente velit architecto! Consequuntur, fugiat.
Iure alias praesentium voluptatum, eveniet reiciendis odit! Eos dolore expedita, neque unde pariatur, laudantium iure, odit reprehenderit placeat ipsa ex aspernatur! Laudantium cum, optio numquam id beatae labore libero repellat.
Vel ratione rerum numquam similique, omnis, dolorum necessitatibus molestiae dicta qui eligendi eius quo. Odio, ratione incidunt molestias suscipit, quos voluptas reiciendis necessitatibus nostrum quo dolore nemo. Temporibus, eligendi velit!
Voluptatum dolor minus voluptatibus consequatur veniam quos dignissimos minima ipsam corporis, deserunt harum ratione expedita eius sit animi incidunt dolorum laboriosam reprehenderit pariatur itaque veritatis quaerat repellat! Nemo, fugit nulla!
Quas, possimus accusantium? Tempore, nemo? Recusandae doloremque, ad corporis harum, provident numquam nisi repellat aut autem voluptate cupiditate natus quae eos. Placeat suscipit ratione eius omnis distinctio debitis magni pariatur.
Deleniti, reiciendis. Et laboriosam aut sapiente deleniti alias cupiditate provident cum magnam perferendis quasi dolorem impedit amet veniam harum facere ducimus, repudiandae minus repellat hic doloremque, qui, iste neque molestiae.
Reprehenderit doloribus, facilis autem soluta velit ex vel recusandae, rem beatae saepe maxime laboriosam accusamus dolore qui quae, dolorum sapiente hic. Delectus, provident facere. Obcaecati, error. Rem dolorem maxime non!
Aspernatur provident similique possimus accusamus fugit ipsa, illum officiis saepe fugiat ut delectus ipsum iste, nulla, sit odio exercitationem sint. Odit magni sequi, voluptatibus et nesciunt excepturi explicabo inventore consectetur?
Cupiditate dolore inventore libero nesciunt voluptatibus autem quidem. Laboriosam commodi beatae sit et minus iste vero pariatur quo, voluptas obcaecati dolorem ex eveniet expedita, iure, unde distinctio in! Cupiditate, hic!
Quae aliquam placeat culpa! Iure distinctio adipisci est. Enim ipsa, voluptate expedita eaque culpa nam saepe quidem perferendis dolorem id maxime sint, deleniti neque odio illo officia optio omnis rerum.
Pariatur, error odio vitae nulla dolor animi repellendus quia, facere saepe eveniet porro deserunt nihil atque nostrum asperiores ratione reprehenderit voluptate quisquam, libero totam voluptatem natus. Dolores itaque modi placeat.
Laudantium autem dolorum reprehenderit magnam voluptatum quisquam harum, aliquid optio est sequi minus culpa blanditiis repudiandae architecto eius, aliquam quam. Totam, distinctio nobis! Esse quidem distinctio minima quia reprehenderit a.
Iure, corrupti libero ad, quidem labore atque dicta illo excepturi inventore, impedit nobis ratione corporis id beatae minus vero dignissimos unde nemo ea voluptates officia pariatur quo hic?
</div></div>